'use client';
import { useEffect, useState } from 'react';
import { AdminCard } from '@/components/admin/ui/AdminCard';
import { AdminTable } from '@/components/admin/ui/AdminTable';
import { FieldLabel, SelectInput, TextArea, TextInput } from '@/components/admin/ui/AdminField';

type Cat = { _id: string; name: string };
type Prod = { _id: string; name: string; slug: string; price: number; stock: number; category?: Cat; attributes?: Record<string,string>; isActive:boolean };

export default function AdminProductsPage() {
  const [items, setItems] = useState<Prod[]>([]); const [cats, setCats] = useState<Cat[]>([]);
  const [form, setForm] = useState({ id:'', name:'', slug:'', shortDescription:'', fullDescription:'', category:'', price:'', stock:'', sku:'', tags:'', attributes:'{}', isActive:true });
  const load = async () => { const [p,c] = await Promise.all([fetch('/api/admin/products'), fetch('/api/admin/categories')]); setItems((await p.json()).items || []); setCats((await c.json()).items || []); };
  useEffect(()=>{void load();},[]);
  const save = async () => { const payload = { ...form, price:Number(form.price), stock:Number(form.stock), tags:form.tags.split(',').map(s=>s.trim()).filter(Boolean), attributes: JSON.parse(form.attributes || '{}') }; const method = form.id ? 'PUT':'POST'; const url = form.id?`/api/admin/products/${form.id}`:'/api/admin/products'; await fetch(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}); setForm({ id:'', name:'', slug:'', shortDescription:'', fullDescription:'', category:'', price:'', stock:'', sku:'', tags:'', attributes:'{}', isActive:true }); void load(); };

  return <main className="space-y-6"><h1 className="text-2xl font-black text-slate-900">مدیریت محصولات</h1>
    <AdminCard title={form.id ? 'ویرایش محصول' : 'ایجاد محصول'}><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><div><FieldLabel text="نام" /><TextInput value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><FieldLabel text="اسلاگ" /><TextInput value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></div><div><FieldLabel text="دسته‌بندی" /><SelectInput value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="">انتخاب دسته‌بندی</option>{cats.map(c=><option key={c._id} value={c._id}>{c.name}</option>)}</SelectInput></div><div><FieldLabel text="SKU" /><TextInput value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})}/></div><div><FieldLabel text="قیمت" /><TextInput value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></div><div><FieldLabel text="موجودی" /><TextInput value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/></div><div className="md:col-span-2"><FieldLabel text="تگ‌ها (کاما)" /><TextInput value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})}/></div><div className="xl:col-span-2"><FieldLabel text="توضیح کوتاه" /><TextInput value={form.shortDescription} onChange={e=>setForm({...form,shortDescription:e.target.value})}/></div><div className="xl:col-span-2"><FieldLabel text="ویژگی‌ها (JSON)" /><TextArea value={form.attributes} onChange={e=>setForm({...form,attributes:e.target.value})}/></div><div className="md:col-span-2 xl:col-span-4"><FieldLabel text="توضیح کامل" /><TextArea value={form.fullDescription} onChange={e=>setForm({...form,fullDescription:e.target.value})}/></div><label className="inline-flex items-center gap-2 text-sm"><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/> محصول فعال باشد</label></div><button className="mt-4 h-11 rounded-xl bg-amber-600 px-4 text-sm font-bold text-white" onClick={save}>{form.id?'ذخیره تغییرات':'ایجاد محصول'}</button></AdminCard>

    <AdminTable head={<tr className="[&>th]:px-4 [&>th]:py-3 [&>th]:text-right"><th>نام</th><th>دسته</th><th>قیمت</th><th>موجودی</th><th>وضعیت</th><th>عملیات</th></tr>}>
      {items.map(p=><tr key={p._id} className="[&>td]:px-4 [&>td]:py-3"><td className="font-medium">{p.name}</td><td>{p.category?.name||'-'}</td><td>{p.price.toLocaleString('fa-IR')}</td><td>{p.stock}</td><td><span className={`rounded-full px-2 py-1 text-xs ${p.isActive?'bg-emerald-100 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{p.isActive?'فعال':'غیرفعال'}</span></td><td className="space-x-3 space-x-reverse"><button className="text-amber-700" onClick={()=>setForm({id:p._id,name:p.name,slug:p.slug,shortDescription:'',fullDescription:'',category:p.category?._id||'',price:String(p.price),stock:String(p.stock),sku:'',tags:'',attributes:JSON.stringify(p.attributes||{},null,0),isActive:p.isActive})}>ویرایش</button><button className="text-red-600" onClick={async()=>{await fetch(`/api/admin/products/${p._id}`,{method:'DELETE'});void load();}}>حذف</button></td></tr>)}
    </AdminTable></main>;
}
