'use client';
import { useEffect, useState } from 'react';
import { AdminCard } from '@/components/admin/ui/AdminCard';
import { FieldLabel, TextInput } from '@/components/admin/ui/AdminField';
import { AdminTable } from '@/components/admin/ui/AdminTable';

type Banner={_id:string;title:string;image:string;link:string;position:string;isActive:boolean};
export default function AdminBannersPage(){const [items,setItems]=useState<Banner[]>([]); const [form,setForm]=useState({id:'',title:'',image:'',link:'/',position:'home',isActive:true}); const load=async()=>setItems((await (await fetch('/api/admin/banners')).json()).items||[]); useEffect(()=>{void load();},[]);
const save=async()=>{const method=form.id?'PUT':'POST'; const url=form.id?`/api/admin/banners/${form.id}`:'/api/admin/banners'; await fetch(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}); setForm({id:'',title:'',image:'',link:'/',position:'home',isActive:true}); void load();};
return <main className="space-y-6"><h1 className="text-2xl font-black">مدیریت بنرها</h1><AdminCard title="ایجاد/ویرایش بنر"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><div><FieldLabel text="عنوان"/><TextInput value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></div><div><FieldLabel text="لینک"/><TextInput value={form.link} onChange={e=>setForm({...form,link:e.target.value})}/></div><div><FieldLabel text="جایگاه"/><TextInput value={form.position} onChange={e=>setForm({...form,position:e.target.value})}/></div><div><FieldLabel text="آدرس تصویر"/><TextInput value={form.image} onChange={e=>setForm({...form,image:e.target.value})}/></div><label className="inline-flex items-center gap-2"><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/> فعال</label></div><button className="mt-4 h-11 rounded-xl bg-amber-600 px-4 text-white" onClick={save}>{form.id?'ذخیره':'ایجاد'}</button></AdminCard><AdminTable head={<tr className="[&>th]:px-4 [&>th]:py-3 text-right"><th>عنوان</th><th>جایگاه</th><th>لینک</th><th>وضعیت</th><th>عملیات</th></tr>}>{items.map(b=><tr key={b._id} className="[&>td]:px-4 [&>td]:py-3"><td>{b.title}</td><td>{b.position}</td><td>{b.link}</td><td>{b.isActive?'فعال':'غیرفعال'}</td><td><button className="text-amber-700" onClick={()=>setForm({id:b._id,title:b.title,image:b.image,link:b.link,position:b.position,isActive:b.isActive})}>ویرایش</button> <button className="text-red-600" onClick={async()=>{await fetch(`/api/admin/banners/${b._id}`,{method:'DELETE'});void load();}}>حذف</button></td></tr>)}</AdminTable></main>; }
