'use client';

import { useEffect, useState } from 'react';
import { AdminCard } from '@/components/admin/ui/AdminCard';
import { FieldLabel, SelectInput, TextInput } from '@/components/admin/ui/AdminField';
import { AdminTable } from '@/components/admin/ui/AdminTable';

type Coupon = { _id: string; code: string; discountType: 'PERCENT'|'FIXED'|'FREE_SHIPPING'; value: number; startsAt: string; expiresAt: string; usageLimit: number; usagePerUserLimit: number; isActive: boolean };

export default function AdminCouponsPage() {
  const [items, setItems] = useState<Coupon[]>([]);
  const [form, setForm] = useState({ id:'', code:'', discountType:'PERCENT', value:'', startsAt:'', expiresAt:'', usageLimit:'0', usagePerUserLimit:'1', minPurchaseAmount:'0', maxDiscountAmount:'', isActive:true });
  const load = async () => setItems((await (await fetch('/api/admin/coupons')).json()).items || []);
  useEffect(() => { void load(); }, []);
  const save = async () => { const method=form.id?'PUT':'POST'; const url=form.id?`/api/admin/coupons/${form.id}`:'/api/admin/coupons'; await fetch(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify({...form, value:Number(form.value||0), usageLimit:Number(form.usageLimit||0), usagePerUserLimit:Number(form.usagePerUserLimit||1), minPurchaseAmount:Number(form.minPurchaseAmount||0), maxDiscountAmount:form.maxDiscountAmount?Number(form.maxDiscountAmount):undefined})}); setForm({ id:'', code:'', discountType:'PERCENT', value:'', startsAt:'', expiresAt:'', usageLimit:'0', usagePerUserLimit:'1', minPurchaseAmount:'0', maxDiscountAmount:'', isActive:true }); void load(); };

  return <main className="space-y-6"><h1 className="text-2xl font-black text-slate-900">مدیریت کدهای تخفیف</h1><AdminCard title={form.id?'ویرایش کد تخفیف':'ایجاد کد تخفیف'}><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><div><FieldLabel text="کد"/><TextInput value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></div><div><FieldLabel text="نوع تخفیف"/><SelectInput value={form.discountType} onChange={e=>setForm({...form,discountType:e.target.value})}><option value="PERCENT">درصدی</option><option value="FIXED">مبلغی</option><option value="FREE_SHIPPING">ارسال رایگان</option></SelectInput></div><div><FieldLabel text="مقدار"/><TextInput value={form.value} onChange={e=>setForm({...form,value:e.target.value})}/></div><div><FieldLabel text="سقف تخفیف"/><TextInput value={form.maxDiscountAmount} onChange={e=>setForm({...form,maxDiscountAmount:e.target.value})}/></div><div><FieldLabel text="حداقل خرید"/><TextInput value={form.minPurchaseAmount} onChange={e=>setForm({...form,minPurchaseAmount:e.target.value})}/></div><div><FieldLabel text="شروع"/><TextInput type="date" value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})}/></div><div><FieldLabel text="انقضا"/><TextInput type="date" value={form.expiresAt} onChange={e=>setForm({...form,expiresAt:e.target.value})}/></div><div><FieldLabel text="حد استفاده"/><TextInput value={form.usageLimit} onChange={e=>setForm({...form,usageLimit:e.target.value})}/></div><div><FieldLabel text="حد هر کاربر"/><TextInput value={form.usagePerUserLimit} onChange={e=>setForm({...form,usagePerUserLimit:e.target.value})}/></div><label className="inline-flex items-center gap-2 pt-8 text-sm"><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/> فعال</label></div><button className="mt-4 h-11 rounded-xl bg-amber-600 px-4 text-white" onClick={save}>{form.id?'ذخیره تغییرات':'ایجاد کد'}</button></AdminCard>

  <AdminTable head={<tr className="[&>th]:px-4 [&>th]:py-3 [&>th]:text-right"><th>کد</th><th>نوع</th><th>مقدار</th><th>بازه</th><th>استفاده</th><th>وضعیت</th><th>عملیات</th></tr>}>
    {items.map(c => <tr key={c._id} className="[&>td]:px-4 [&>td]:py-3"><td className="font-bold">{c.code}</td><td>{c.discountType}</td><td>{c.value}</td><td>{new Date(c.startsAt).toLocaleDateString('fa-IR')} - {new Date(c.expiresAt).toLocaleDateString('fa-IR')}</td><td>{c.usagePerUserLimit}/{c.usageLimit || '∞'}</td><td><span className={`rounded-full px-2 py-1 text-xs ${c.isActive?'bg-emerald-100 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{c.isActive?'فعال':'غیرفعال'}</span></td><td className="space-x-3 space-x-reverse"><button className="text-amber-700" onClick={()=>setForm({id:c._id,code:c.code,discountType:c.discountType,value:String(c.value),startsAt:c.startsAt?.slice(0,10),expiresAt:c.expiresAt?.slice(0,10),usageLimit:String(c.usageLimit||0),usagePerUserLimit:String(c.usagePerUserLimit||1),minPurchaseAmount:'0',maxDiscountAmount:'',isActive:c.isActive})}>ویرایش</button><button className="text-red-600" onClick={async()=>{await fetch(`/api/admin/coupons/${c._id}`,{method:'DELETE'});void load();}}>حذف</button></td></tr>)}
  </AdminTable></main>;
}
